/*
 * Mastercard Digital Enablement Service Customer Service API
 * The MDES Customer Service API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.mastercard.model;

import java.util.Objects;
import com.example.mastercard.model.AuditInfo;
import com.example.mastercard.model.DisablePaymentChannelsDataDisabledPaymentChannels;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.mastercard.JSON;

/**
 * DisablePaymentChannelsData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T17:08:41.015538669-03:00[America/Sao_Paulo]")
public class DisablePaymentChannelsData {
  public static final String SERIALIZED_NAME_TOKEN_UNIQUE_REFERENCE = "TokenUniqueReference";
  @SerializedName(SERIALIZED_NAME_TOKEN_UNIQUE_REFERENCE)
  private String tokenUniqueReference;

  public static final String SERIALIZED_NAME_DISABLED_PAYMENT_CHANNELS = "DisabledPaymentChannels";
  @SerializedName(SERIALIZED_NAME_DISABLED_PAYMENT_CHANNELS)
  private DisablePaymentChannelsDataDisabledPaymentChannels disabledPaymentChannels;

  public static final String SERIALIZED_NAME_ENABLE_ALL_PAYMENT_CHANNELS = "EnableAllPaymentChannels";
  @SerializedName(SERIALIZED_NAME_ENABLE_ALL_PAYMENT_CHANNELS)
  private String enableAllPaymentChannels;

  public static final String SERIALIZED_NAME_AUDIT_INFO = "AuditInfo";
  @SerializedName(SERIALIZED_NAME_AUDIT_INFO)
  private AuditInfo auditInfo;

  public DisablePaymentChannelsData() {
  }

  public DisablePaymentChannelsData tokenUniqueReference(String tokenUniqueReference) {
    this.tokenUniqueReference = tokenUniqueReference;
    return this;
  }

   /**
   * Unique reference of the token to be updated. Conditional field, used for updating a single token.
   * @return tokenUniqueReference
  **/
  @javax.annotation.Nonnull
  public String getTokenUniqueReference() {
    return tokenUniqueReference;
  }

  public void setTokenUniqueReference(String tokenUniqueReference) {
    this.tokenUniqueReference = tokenUniqueReference;
  }


  public DisablePaymentChannelsData disabledPaymentChannels(DisablePaymentChannelsDataDisabledPaymentChannels disabledPaymentChannels) {
    this.disabledPaymentChannels = disabledPaymentChannels;
    return this;
  }

   /**
   * Get disabledPaymentChannels
   * @return disabledPaymentChannels
  **/
  @javax.annotation.Nullable
  public DisablePaymentChannelsDataDisabledPaymentChannels getDisabledPaymentChannels() {
    return disabledPaymentChannels;
  }

  public void setDisabledPaymentChannels(DisablePaymentChannelsDataDisabledPaymentChannels disabledPaymentChannels) {
    this.disabledPaymentChannels = disabledPaymentChannels;
  }


  public DisablePaymentChannelsData enableAllPaymentChannels(String enableAllPaymentChannels) {
    this.enableAllPaymentChannels = enableAllPaymentChannels;
    return this;
  }

   /**
   * Used to enable all payment channels.  Will be assumed to be false if not present.
   * @return enableAllPaymentChannels
  **/
  @javax.annotation.Nullable
  public String getEnableAllPaymentChannels() {
    return enableAllPaymentChannels;
  }

  public void setEnableAllPaymentChannels(String enableAllPaymentChannels) {
    this.enableAllPaymentChannels = enableAllPaymentChannels;
  }


  public DisablePaymentChannelsData auditInfo(AuditInfo auditInfo) {
    this.auditInfo = auditInfo;
    return this;
  }

   /**
   * Get auditInfo
   * @return auditInfo
  **/
  @javax.annotation.Nonnull
  public AuditInfo getAuditInfo() {
    return auditInfo;
  }

  public void setAuditInfo(AuditInfo auditInfo) {
    this.auditInfo = auditInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisablePaymentChannelsData disablePaymentChannelsData = (DisablePaymentChannelsData) o;
    return Objects.equals(this.tokenUniqueReference, disablePaymentChannelsData.tokenUniqueReference) &&
        Objects.equals(this.disabledPaymentChannels, disablePaymentChannelsData.disabledPaymentChannels) &&
        Objects.equals(this.enableAllPaymentChannels, disablePaymentChannelsData.enableAllPaymentChannels) &&
        Objects.equals(this.auditInfo, disablePaymentChannelsData.auditInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenUniqueReference, disabledPaymentChannels, enableAllPaymentChannels, auditInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisablePaymentChannelsData {\n");
    sb.append("    tokenUniqueReference: ").append(toIndentedString(tokenUniqueReference)).append("\n");
    sb.append("    disabledPaymentChannels: ").append(toIndentedString(disabledPaymentChannels)).append("\n");
    sb.append("    enableAllPaymentChannels: ").append(toIndentedString(enableAllPaymentChannels)).append("\n");
    sb.append("    auditInfo: ").append(toIndentedString(auditInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("TokenUniqueReference");
    openapiFields.add("DisabledPaymentChannels");
    openapiFields.add("EnableAllPaymentChannels");
    openapiFields.add("AuditInfo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("TokenUniqueReference");
    openapiRequiredFields.add("AuditInfo");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DisablePaymentChannelsData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DisablePaymentChannelsData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DisablePaymentChannelsData is not found in the empty JSON string", DisablePaymentChannelsData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DisablePaymentChannelsData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DisablePaymentChannelsData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DisablePaymentChannelsData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("TokenUniqueReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TokenUniqueReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TokenUniqueReference").toString()));
      }
      // validate the optional field `DisabledPaymentChannels`
      if (jsonObj.get("DisabledPaymentChannels") != null && !jsonObj.get("DisabledPaymentChannels").isJsonNull()) {
        DisablePaymentChannelsDataDisabledPaymentChannels.validateJsonElement(jsonObj.get("DisabledPaymentChannels"));
      }
      if ((jsonObj.get("EnableAllPaymentChannels") != null && !jsonObj.get("EnableAllPaymentChannels").isJsonNull()) && !jsonObj.get("EnableAllPaymentChannels").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EnableAllPaymentChannels` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EnableAllPaymentChannels").toString()));
      }
      // validate the required field `AuditInfo`
      AuditInfo.validateJsonElement(jsonObj.get("AuditInfo"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DisablePaymentChannelsData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DisablePaymentChannelsData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DisablePaymentChannelsData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DisablePaymentChannelsData.class));

       return (TypeAdapter<T>) new TypeAdapter<DisablePaymentChannelsData>() {
           @Override
           public void write(JsonWriter out, DisablePaymentChannelsData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DisablePaymentChannelsData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DisablePaymentChannelsData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DisablePaymentChannelsData
  * @throws IOException if the JSON string is invalid with respect to DisablePaymentChannelsData
  */
  public static DisablePaymentChannelsData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DisablePaymentChannelsData.class);
  }

 /**
  * Convert an instance of DisablePaymentChannelsData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

