/*
 * Mastercard Digital Enablement Service Customer Service API
 * The MDES Customer Service API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.mastercard.model;

import java.util.Objects;
import com.example.mastercard.model.AuditInfo;
import com.example.mastercard.model.CurrentFinancialAccountInformation;
import com.example.mastercard.model.UpdateEncryptedAccountInformation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.mastercard.JSON;

/**
 * TokenUpdateData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T17:08:41.015538669-03:00[America/Sao_Paulo]")
public class TokenUpdateData {
  public static final String SERIALIZED_NAME_ENCRYPTED_ACCOUNT_INFORMATION = "EncryptedAccountInformation";
  @SerializedName(SERIALIZED_NAME_ENCRYPTED_ACCOUNT_INFORMATION)
  private UpdateEncryptedAccountInformation encryptedAccountInformation;

  public static final String SERIALIZED_NAME_TOKEN_UNIQUE_REFERENCE = "TokenUniqueReference";
  @SerializedName(SERIALIZED_NAME_TOKEN_UNIQUE_REFERENCE)
  private String tokenUniqueReference;

  public static final String SERIALIZED_NAME_ISSUER_PRODUCT_CONFIGURATION_ID = "IssuerProductConfigurationId";
  @SerializedName(SERIALIZED_NAME_ISSUER_PRODUCT_CONFIGURATION_ID)
  private String issuerProductConfigurationId;

  public static final String SERIALIZED_NAME_REMOVE_ALTERNATE_ACCOUNT_IDENTIFIER_SUFFIX = "RemoveAlternateAccountIdentifierSuffix";
  @SerializedName(SERIALIZED_NAME_REMOVE_ALTERNATE_ACCOUNT_IDENTIFIER_SUFFIX)
  private String removeAlternateAccountIdentifierSuffix;

  public static final String SERIALIZED_NAME_UPDATE_WALLET_PROVIDER_INDICATOR = "UpdateWalletProviderIndicator";
  @SerializedName(SERIALIZED_NAME_UPDATE_WALLET_PROVIDER_INDICATOR)
  private String updateWalletProviderIndicator;

  public static final String SERIALIZED_NAME_COMMENT_TEXT = "CommentText";
  @SerializedName(SERIALIZED_NAME_COMMENT_TEXT)
  private String commentText;

  public static final String SERIALIZED_NAME_AUDIT_INFO = "AuditInfo";
  @SerializedName(SERIALIZED_NAME_AUDIT_INFO)
  private AuditInfo auditInfo;

  public static final String SERIALIZED_NAME_CURRENT_FINANCIAL_ACCOUNT_INFORMATION = "CurrentFinancialAccountInformation";
  @SerializedName(SERIALIZED_NAME_CURRENT_FINANCIAL_ACCOUNT_INFORMATION)
  private CurrentFinancialAccountInformation currentFinancialAccountInformation;

  public TokenUpdateData() {
  }

  public TokenUpdateData encryptedAccountInformation(UpdateEncryptedAccountInformation encryptedAccountInformation) {
    this.encryptedAccountInformation = encryptedAccountInformation;
    return this;
  }

   /**
   * Get encryptedAccountInformation
   * @return encryptedAccountInformation
  **/
  @javax.annotation.Nullable
  public UpdateEncryptedAccountInformation getEncryptedAccountInformation() {
    return encryptedAccountInformation;
  }

  public void setEncryptedAccountInformation(UpdateEncryptedAccountInformation encryptedAccountInformation) {
    this.encryptedAccountInformation = encryptedAccountInformation;
  }


  public TokenUpdateData tokenUniqueReference(String tokenUniqueReference) {
    this.tokenUniqueReference = tokenUniqueReference;
    return this;
  }

   /**
   * Unique reference of the token to be updated. Conditional field, used for updating a single token and not used when CurrentAccountPan is present. Supply either the TokenUniqueReference or the CurrentAccountPan.
   * @return tokenUniqueReference
  **/
  @javax.annotation.Nullable
  public String getTokenUniqueReference() {
    return tokenUniqueReference;
  }

  public void setTokenUniqueReference(String tokenUniqueReference) {
    this.tokenUniqueReference = tokenUniqueReference;
  }


  public TokenUpdateData issuerProductConfigurationId(String issuerProductConfigurationId) {
    this.issuerProductConfigurationId = issuerProductConfigurationId;
    return this;
  }

   /**
   * New product configuration ID to be applied to the updated token(s). Conditional field, must not be present if any of the following are present - NewAccountPan, ExpirationDate, AccountPanSequenceNumber, NewFinancialAccountId.
   * @return issuerProductConfigurationId
  **/
  @javax.annotation.Nullable
  public String getIssuerProductConfigurationId() {
    return issuerProductConfigurationId;
  }

  public void setIssuerProductConfigurationId(String issuerProductConfigurationId) {
    this.issuerProductConfigurationId = issuerProductConfigurationId;
  }


  public TokenUpdateData removeAlternateAccountIdentifierSuffix(String removeAlternateAccountIdentifierSuffix) {
    this.removeAlternateAccountIdentifierSuffix = removeAlternateAccountIdentifierSuffix;
    return this;
  }

   /**
   * Indicates whether the aleternate account identifier suffix associated to a token should be removed as part of the request. Value values:   * \&quot;true\&quot; - Remove the alternate account identifier associated to a token   * \&quot;false\&quot; - Do not remove the alternate account identifier associated to a token 
   * @return removeAlternateAccountIdentifierSuffix
  **/
  @javax.annotation.Nullable
  public String getRemoveAlternateAccountIdentifierSuffix() {
    return removeAlternateAccountIdentifierSuffix;
  }

  public void setRemoveAlternateAccountIdentifierSuffix(String removeAlternateAccountIdentifierSuffix) {
    this.removeAlternateAccountIdentifierSuffix = removeAlternateAccountIdentifierSuffix;
  }


  public TokenUpdateData updateWalletProviderIndicator(String updateWalletProviderIndicator) {
    this.updateWalletProviderIndicator = updateWalletProviderIndicator;
    return this;
  }

   /**
   * Indicates whether the updated token information should be provided to the Wallet Provider. Valid values:   * \&quot;0\&quot; - Pass the updated information to the Wallet Provider   * \&quot;1\&quot; - Do not pass the updated information to the Wallet Provider. Optional parameter. The default is 1 if not present. 
   * @return updateWalletProviderIndicator
  **/
  @javax.annotation.Nullable
  public String getUpdateWalletProviderIndicator() {
    return updateWalletProviderIndicator;
  }

  public void setUpdateWalletProviderIndicator(String updateWalletProviderIndicator) {
    this.updateWalletProviderIndicator = updateWalletProviderIndicator;
  }


  public TokenUpdateData commentText(String commentText) {
    this.commentText = commentText;
    return this;
  }

   /**
   * Comment related to the updated token(s). Maximum length 500 characters.
   * @return commentText
  **/
  @javax.annotation.Nullable
  public String getCommentText() {
    return commentText;
  }

  public void setCommentText(String commentText) {
    this.commentText = commentText;
  }


  public TokenUpdateData auditInfo(AuditInfo auditInfo) {
    this.auditInfo = auditInfo;
    return this;
  }

   /**
   * Get auditInfo
   * @return auditInfo
  **/
  @javax.annotation.Nonnull
  public AuditInfo getAuditInfo() {
    return auditInfo;
  }

  public void setAuditInfo(AuditInfo auditInfo) {
    this.auditInfo = auditInfo;
  }


  public TokenUpdateData currentFinancialAccountInformation(CurrentFinancialAccountInformation currentFinancialAccountInformation) {
    this.currentFinancialAccountInformation = currentFinancialAccountInformation;
    return this;
  }

   /**
   * Get currentFinancialAccountInformation
   * @return currentFinancialAccountInformation
  **/
  @javax.annotation.Nullable
  public CurrentFinancialAccountInformation getCurrentFinancialAccountInformation() {
    return currentFinancialAccountInformation;
  }

  public void setCurrentFinancialAccountInformation(CurrentFinancialAccountInformation currentFinancialAccountInformation) {
    this.currentFinancialAccountInformation = currentFinancialAccountInformation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenUpdateData tokenUpdateData = (TokenUpdateData) o;
    return Objects.equals(this.encryptedAccountInformation, tokenUpdateData.encryptedAccountInformation) &&
        Objects.equals(this.tokenUniqueReference, tokenUpdateData.tokenUniqueReference) &&
        Objects.equals(this.issuerProductConfigurationId, tokenUpdateData.issuerProductConfigurationId) &&
        Objects.equals(this.removeAlternateAccountIdentifierSuffix, tokenUpdateData.removeAlternateAccountIdentifierSuffix) &&
        Objects.equals(this.updateWalletProviderIndicator, tokenUpdateData.updateWalletProviderIndicator) &&
        Objects.equals(this.commentText, tokenUpdateData.commentText) &&
        Objects.equals(this.auditInfo, tokenUpdateData.auditInfo) &&
        Objects.equals(this.currentFinancialAccountInformation, tokenUpdateData.currentFinancialAccountInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encryptedAccountInformation, tokenUniqueReference, issuerProductConfigurationId, removeAlternateAccountIdentifierSuffix, updateWalletProviderIndicator, commentText, auditInfo, currentFinancialAccountInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenUpdateData {\n");
    sb.append("    encryptedAccountInformation: ").append(toIndentedString(encryptedAccountInformation)).append("\n");
    sb.append("    tokenUniqueReference: ").append(toIndentedString(tokenUniqueReference)).append("\n");
    sb.append("    issuerProductConfigurationId: ").append(toIndentedString(issuerProductConfigurationId)).append("\n");
    sb.append("    removeAlternateAccountIdentifierSuffix: ").append(toIndentedString(removeAlternateAccountIdentifierSuffix)).append("\n");
    sb.append("    updateWalletProviderIndicator: ").append(toIndentedString(updateWalletProviderIndicator)).append("\n");
    sb.append("    commentText: ").append(toIndentedString(commentText)).append("\n");
    sb.append("    auditInfo: ").append(toIndentedString(auditInfo)).append("\n");
    sb.append("    currentFinancialAccountInformation: ").append(toIndentedString(currentFinancialAccountInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("EncryptedAccountInformation");
    openapiFields.add("TokenUniqueReference");
    openapiFields.add("IssuerProductConfigurationId");
    openapiFields.add("RemoveAlternateAccountIdentifierSuffix");
    openapiFields.add("UpdateWalletProviderIndicator");
    openapiFields.add("CommentText");
    openapiFields.add("AuditInfo");
    openapiFields.add("CurrentFinancialAccountInformation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("AuditInfo");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TokenUpdateData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TokenUpdateData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TokenUpdateData is not found in the empty JSON string", TokenUpdateData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TokenUpdateData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TokenUpdateData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TokenUpdateData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `EncryptedAccountInformation`
      if (jsonObj.get("EncryptedAccountInformation") != null && !jsonObj.get("EncryptedAccountInformation").isJsonNull()) {
        UpdateEncryptedAccountInformation.validateJsonElement(jsonObj.get("EncryptedAccountInformation"));
      }
      if ((jsonObj.get("TokenUniqueReference") != null && !jsonObj.get("TokenUniqueReference").isJsonNull()) && !jsonObj.get("TokenUniqueReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TokenUniqueReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TokenUniqueReference").toString()));
      }
      if ((jsonObj.get("IssuerProductConfigurationId") != null && !jsonObj.get("IssuerProductConfigurationId").isJsonNull()) && !jsonObj.get("IssuerProductConfigurationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `IssuerProductConfigurationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("IssuerProductConfigurationId").toString()));
      }
      if ((jsonObj.get("RemoveAlternateAccountIdentifierSuffix") != null && !jsonObj.get("RemoveAlternateAccountIdentifierSuffix").isJsonNull()) && !jsonObj.get("RemoveAlternateAccountIdentifierSuffix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RemoveAlternateAccountIdentifierSuffix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RemoveAlternateAccountIdentifierSuffix").toString()));
      }
      if ((jsonObj.get("UpdateWalletProviderIndicator") != null && !jsonObj.get("UpdateWalletProviderIndicator").isJsonNull()) && !jsonObj.get("UpdateWalletProviderIndicator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `UpdateWalletProviderIndicator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("UpdateWalletProviderIndicator").toString()));
      }
      if ((jsonObj.get("CommentText") != null && !jsonObj.get("CommentText").isJsonNull()) && !jsonObj.get("CommentText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CommentText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CommentText").toString()));
      }
      // validate the required field `AuditInfo`
      AuditInfo.validateJsonElement(jsonObj.get("AuditInfo"));
      // validate the optional field `CurrentFinancialAccountInformation`
      if (jsonObj.get("CurrentFinancialAccountInformation") != null && !jsonObj.get("CurrentFinancialAccountInformation").isJsonNull()) {
        CurrentFinancialAccountInformation.validateJsonElement(jsonObj.get("CurrentFinancialAccountInformation"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TokenUpdateData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TokenUpdateData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TokenUpdateData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TokenUpdateData.class));

       return (TypeAdapter<T>) new TypeAdapter<TokenUpdateData>() {
           @Override
           public void write(JsonWriter out, TokenUpdateData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TokenUpdateData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TokenUpdateData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TokenUpdateData
  * @throws IOException if the JSON string is invalid with respect to TokenUpdateData
  */
  public static TokenUpdateData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TokenUpdateData.class);
  }

 /**
  * Convert an instance of TokenUpdateData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

