/*
 * Mastercard Digital Enablement Service Customer Service API
 * The MDES Customer Service API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.mastercard.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.mastercard.JSON;

/**
 * Transaction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T17:08:41.015538669-03:00[America/Sao_Paulo]")
public class Transaction {
  public static final String SERIALIZED_NAME_TRANSACTION_DATE_TIME = "TransactionDateTime";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_DATE_TIME)
  private String transactionDateTime;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "CurrencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_TRANSACTION_AMOUNT = "TransactionAmount";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_AMOUNT)
  private String transactionAmount;

  public static final String SERIALIZED_NAME_TRANSACTION_TYPE_CODE = "TransactionTypeCode";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TYPE_CODE)
  private String transactionTypeCode;

  public static final String SERIALIZED_NAME_TRANSACTION_TYPE_DESCRIPTION = "TransactionTypeDescription";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TYPE_DESCRIPTION)
  private String transactionTypeDescription;

  public static final String SERIALIZED_NAME_TRANSACTION_STATUS_CODE = "TransactionStatusCode";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_STATUS_CODE)
  private String transactionStatusCode;

  public static final String SERIALIZED_NAME_MERCHANT_NAME = "MerchantName";
  @SerializedName(SERIALIZED_NAME_MERCHANT_NAME)
  private String merchantName;

  public static final String SERIALIZED_NAME_MERCHANT_CATEGORY_CODE = "MerchantCategoryCode";
  @SerializedName(SERIALIZED_NAME_MERCHANT_CATEGORY_CODE)
  private String merchantCategoryCode;

  public static final String SERIALIZED_NAME_MERCHANT_CATEGORY_DESCRIPTION = "MerchantCategoryDescription";
  @SerializedName(SERIALIZED_NAME_MERCHANT_CATEGORY_DESCRIPTION)
  private String merchantCategoryDescription;

  public static final String SERIALIZED_NAME_PO_S_ENTRY_MODE = "POSEntryMode";
  @SerializedName(SERIALIZED_NAME_PO_S_ENTRY_MODE)
  private String poSEntryMode;

  public Transaction() {
  }

  public Transaction transactionDateTime(String transactionDateTime) {
    this.transactionDateTime = transactionDateTime;
    return this;
  }

   /**
   * Date and time the comment was updated. String, YYYY-MM-DDThh:mm:ssTZD .
   * @return transactionDateTime
  **/
  @javax.annotation.Nonnull
  public String getTransactionDateTime() {
    return transactionDateTime;
  }

  public void setTransactionDateTime(String transactionDateTime) {
    this.transactionDateTime = transactionDateTime;
  }


  public Transaction currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * ISO-4217 currency code (3-letter alphabetic currency code).
   * @return currencyCode
  **/
  @javax.annotation.Nonnull
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public Transaction transactionAmount(String transactionAmount) {
    this.transactionAmount = transactionAmount;
    return this;
  }

   /**
   * Amount of the transaction formatted with decimal places.
   * @return transactionAmount
  **/
  @javax.annotation.Nonnull
  public String getTransactionAmount() {
    return transactionAmount;
  }

  public void setTransactionAmount(String transactionAmount) {
    this.transactionAmount = transactionAmount;
  }


  public Transaction transactionTypeCode(String transactionTypeCode) {
    this.transactionTypeCode = transactionTypeCode;
    return this;
  }

   /**
   * Type of transaction. Valid values:   * \&quot;PURCH\&quot; - Purchase   * \&quot;PURCB\&quot; - Purchase with Cashback   * \&quot;REFND\&quot; - Refund   * \&quot;AFD\&quot; - Purchase Pre-Auth AFD   * \&quot;CLRRF\&quot; - Clearing Refund   * \&quot;NAFD\&quot; - Purchase Pre-Auth Non-AFD 
   * @return transactionTypeCode
  **/
  @javax.annotation.Nonnull
  public String getTransactionTypeCode() {
    return transactionTypeCode;
  }

  public void setTransactionTypeCode(String transactionTypeCode) {
    this.transactionTypeCode = transactionTypeCode;
  }


  public Transaction transactionTypeDescription(String transactionTypeDescription) {
    this.transactionTypeDescription = transactionTypeDescription;
    return this;
  }

   /**
   * Description of the transaction type.
   * @return transactionTypeDescription
  **/
  @javax.annotation.Nonnull
  public String getTransactionTypeDescription() {
    return transactionTypeDescription;
  }

  public void setTransactionTypeDescription(String transactionTypeDescription) {
    this.transactionTypeDescription = transactionTypeDescription;
  }


  public Transaction transactionStatusCode(String transactionStatusCode) {
    this.transactionStatusCode = transactionStatusCode;
    return this;
  }

   /**
   * Transaction status. Valid values:   * \&quot;AUTH\&quot; - Authorized   * \&quot;COMP\&quot; - Completed   * \&quot;DCLN\&quot; - Declined   * \&quot;PAUTH\&quot; - Pre-Authorized   * \&quot;PAUTC\&quot; - Pre-Authorization Completed   * \&quot;PAUTD\&quot; - Pre-Authorization Declined   * \&quot;REFND\&quot; - Refunded 
   * @return transactionStatusCode
  **/
  @javax.annotation.Nonnull
  public String getTransactionStatusCode() {
    return transactionStatusCode;
  }

  public void setTransactionStatusCode(String transactionStatusCode) {
    this.transactionStatusCode = transactionStatusCode;
  }


  public Transaction merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

   /**
   * Name of the merchant. Conditional field. When available, it must be included in the response.
   * @return merchantName
  **/
  @javax.annotation.Nullable
  public String getMerchantName() {
    return merchantName;
  }

  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }


  public Transaction merchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

   /**
   * Merchant category of the merchant. Conditional field. When available, it must be included in the response.
   * @return merchantCategoryCode
  **/
  @javax.annotation.Nullable
  public String getMerchantCategoryCode() {
    return merchantCategoryCode;
  }

  public void setMerchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }


  public Transaction merchantCategoryDescription(String merchantCategoryDescription) {
    this.merchantCategoryDescription = merchantCategoryDescription;
    return this;
  }

   /**
   * Description of the merchant category.
   * @return merchantCategoryDescription
  **/
  @javax.annotation.Nonnull
  public String getMerchantCategoryDescription() {
    return merchantCategoryDescription;
  }

  public void setMerchantCategoryDescription(String merchantCategoryDescription) {
    this.merchantCategoryDescription = merchantCategoryDescription;
  }


  public Transaction poSEntryMode(String poSEntryMode) {
    this.poSEntryMode = poSEntryMode;
    return this;
  }

   /**
   * Indicates the mode by which transaction data was collected at the merchant. Conditional field. When available, it must be included in the response.  Valid values:   * \&quot;07\&quot; - Contactless M/Chip transaction   * \&quot;09\&quot; - Digital Secure Remote Payment containing EMV data   * \&quot;81\&quot; - Digital Secure Remote Payment containing UCAF data or CoF   * \&quot;82\&quot; - CoF - PAN auto entry via server   * \&quot;90\&quot; - Dynamic Magnetic Strip Data   * \&quot;91\&quot; - Contactless magnetic stripe 
   * @return poSEntryMode
  **/
  @javax.annotation.Nullable
  public String getPoSEntryMode() {
    return poSEntryMode;
  }

  public void setPoSEntryMode(String poSEntryMode) {
    this.poSEntryMode = poSEntryMode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.transactionDateTime, transaction.transactionDateTime) &&
        Objects.equals(this.currencyCode, transaction.currencyCode) &&
        Objects.equals(this.transactionAmount, transaction.transactionAmount) &&
        Objects.equals(this.transactionTypeCode, transaction.transactionTypeCode) &&
        Objects.equals(this.transactionTypeDescription, transaction.transactionTypeDescription) &&
        Objects.equals(this.transactionStatusCode, transaction.transactionStatusCode) &&
        Objects.equals(this.merchantName, transaction.merchantName) &&
        Objects.equals(this.merchantCategoryCode, transaction.merchantCategoryCode) &&
        Objects.equals(this.merchantCategoryDescription, transaction.merchantCategoryDescription) &&
        Objects.equals(this.poSEntryMode, transaction.poSEntryMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionDateTime, currencyCode, transactionAmount, transactionTypeCode, transactionTypeDescription, transactionStatusCode, merchantName, merchantCategoryCode, merchantCategoryDescription, poSEntryMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    transactionDateTime: ").append(toIndentedString(transactionDateTime)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    transactionTypeCode: ").append(toIndentedString(transactionTypeCode)).append("\n");
    sb.append("    transactionTypeDescription: ").append(toIndentedString(transactionTypeDescription)).append("\n");
    sb.append("    transactionStatusCode: ").append(toIndentedString(transactionStatusCode)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("    merchantCategoryDescription: ").append(toIndentedString(merchantCategoryDescription)).append("\n");
    sb.append("    poSEntryMode: ").append(toIndentedString(poSEntryMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("TransactionDateTime");
    openapiFields.add("CurrencyCode");
    openapiFields.add("TransactionAmount");
    openapiFields.add("TransactionTypeCode");
    openapiFields.add("TransactionTypeDescription");
    openapiFields.add("TransactionStatusCode");
    openapiFields.add("MerchantName");
    openapiFields.add("MerchantCategoryCode");
    openapiFields.add("MerchantCategoryDescription");
    openapiFields.add("POSEntryMode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("TransactionDateTime");
    openapiRequiredFields.add("CurrencyCode");
    openapiRequiredFields.add("TransactionAmount");
    openapiRequiredFields.add("TransactionTypeCode");
    openapiRequiredFields.add("TransactionTypeDescription");
    openapiRequiredFields.add("TransactionStatusCode");
    openapiRequiredFields.add("MerchantCategoryDescription");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Transaction
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Transaction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Transaction is not found in the empty JSON string", Transaction.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Transaction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Transaction` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Transaction.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("TransactionDateTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransactionDateTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransactionDateTime").toString()));
      }
      if (!jsonObj.get("CurrencyCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CurrencyCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CurrencyCode").toString()));
      }
      if (!jsonObj.get("TransactionAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransactionAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransactionAmount").toString()));
      }
      if (!jsonObj.get("TransactionTypeCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransactionTypeCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransactionTypeCode").toString()));
      }
      if (!jsonObj.get("TransactionTypeDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransactionTypeDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransactionTypeDescription").toString()));
      }
      if (!jsonObj.get("TransactionStatusCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TransactionStatusCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TransactionStatusCode").toString()));
      }
      if ((jsonObj.get("MerchantName") != null && !jsonObj.get("MerchantName").isJsonNull()) && !jsonObj.get("MerchantName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MerchantName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MerchantName").toString()));
      }
      if ((jsonObj.get("MerchantCategoryCode") != null && !jsonObj.get("MerchantCategoryCode").isJsonNull()) && !jsonObj.get("MerchantCategoryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MerchantCategoryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MerchantCategoryCode").toString()));
      }
      if (!jsonObj.get("MerchantCategoryDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MerchantCategoryDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MerchantCategoryDescription").toString()));
      }
      if ((jsonObj.get("POSEntryMode") != null && !jsonObj.get("POSEntryMode").isJsonNull()) && !jsonObj.get("POSEntryMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `POSEntryMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("POSEntryMode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Transaction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Transaction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Transaction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Transaction.class));

       return (TypeAdapter<T>) new TypeAdapter<Transaction>() {
           @Override
           public void write(JsonWriter out, Transaction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Transaction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Transaction given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Transaction
  * @throws IOException if the JSON string is invalid with respect to Transaction
  */
  public static Transaction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Transaction.class);
  }

 /**
  * Convert an instance of Transaction to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

