/*
 * Mastercard Digital Enablement Service Customer Service API
 * The MDES Customer Service API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.mastercard.api;

import com.example.mastercard.ApiCallback;
import com.example.mastercard.ApiClient;
import com.example.mastercard.ApiException;
import com.example.mastercard.ApiResponse;
import com.example.mastercard.Configuration;
import com.example.mastercard.Pair;
import com.example.mastercard.ProgressRequestBody;
import com.example.mastercard.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.example.mastercard.model.TokenComments;
import com.example.mastercard.model.TokenCommentsResults;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TokenCommentsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TokenCommentsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TokenCommentsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for tokenComments
     * @param id Static endpoint iteration number (Not API Version) (required)
     * @param tokenComments JSON object containing parameters for obtaining all comments assocaited to a token (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response containing all of the comments for a given token </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tokenCommentsCall(String id, TokenComments tokenComments, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = tokenComments;

        // create path and map variables
        String localVarPath = "/{id}/token/comments"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call tokenCommentsValidateBeforeCall(String id, TokenComments tokenComments, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling tokenComments(Async)");
        }

        // verify the required parameter 'tokenComments' is set
        if (tokenComments == null) {
            throw new ApiException("Missing the required parameter 'tokenComments' when calling tokenComments(Async)");
        }

        return tokenCommentsCall(id, tokenComments, _callback);

    }

    /**
     * Displays comments previously submitted on a token.
     * Used to retrieve all comments associated with a token. Typically the response includes comments created earlier by Issuer Customer Service representatives detailing additional information about a particular inquiry or event. There may also be comments with warnings of potential fraud. These comments are created automatically by the MDES system when a Token requestor indicates a high risk of fraud during digitization. 
     * @param id Static endpoint iteration number (Not API Version) (required)
     * @param tokenComments JSON object containing parameters for obtaining all comments assocaited to a token (required)
     * @return TokenCommentsResults
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response containing all of the comments for a given token </td><td>  -  </td></tr>
     </table>
     */
    public TokenCommentsResults tokenComments(String id, TokenComments tokenComments) throws ApiException {
        ApiResponse<TokenCommentsResults> localVarResp = tokenCommentsWithHttpInfo(id, tokenComments);
        return localVarResp.getData();
    }

    /**
     * Displays comments previously submitted on a token.
     * Used to retrieve all comments associated with a token. Typically the response includes comments created earlier by Issuer Customer Service representatives detailing additional information about a particular inquiry or event. There may also be comments with warnings of potential fraud. These comments are created automatically by the MDES system when a Token requestor indicates a high risk of fraud during digitization. 
     * @param id Static endpoint iteration number (Not API Version) (required)
     * @param tokenComments JSON object containing parameters for obtaining all comments assocaited to a token (required)
     * @return ApiResponse&lt;TokenCommentsResults&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response containing all of the comments for a given token </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TokenCommentsResults> tokenCommentsWithHttpInfo(String id, TokenComments tokenComments) throws ApiException {
        okhttp3.Call localVarCall = tokenCommentsValidateBeforeCall(id, tokenComments, null);
        Type localVarReturnType = new TypeToken<TokenCommentsResults>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Displays comments previously submitted on a token. (asynchronously)
     * Used to retrieve all comments associated with a token. Typically the response includes comments created earlier by Issuer Customer Service representatives detailing additional information about a particular inquiry or event. There may also be comments with warnings of potential fraud. These comments are created automatically by the MDES system when a Token requestor indicates a high risk of fraud during digitization. 
     * @param id Static endpoint iteration number (Not API Version) (required)
     * @param tokenComments JSON object containing parameters for obtaining all comments assocaited to a token (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response containing all of the comments for a given token </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tokenCommentsAsync(String id, TokenComments tokenComments, final ApiCallback<TokenCommentsResults> _callback) throws ApiException {

        okhttp3.Call localVarCall = tokenCommentsValidateBeforeCall(id, tokenComments, _callback);
        Type localVarReturnType = new TypeToken<TokenCommentsResults>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
